/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package RomanNumeral

object RomanNumeralConverter {
    private val romans = listOf(
            1000 to "M",
            900  to "CM",
            500  to "D",
            400  to "CD",
            100  to "C",
            90   to "XC",
            50   to "L",
            40   to "XL",
            10   to "X",
            9    to "IX",
            5    to "V",
            4    to "IV",
            1    to "I").toMap()

    fun fromArabic(arabic: Int): String {
        var roman = ""
        var arabicDigit = arabic

        romans.forEach { (digit: Int, glyph: String) ->
            while (arabicDigit >= digit) {
                roman += glyph
                arabicDigit -= digit
            }
        }
        return roman
    }
}
