/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package RomanNumeral

object RomanNumeralConverter {
    private val romans = listOf(1000 to "M", 500 to "D", 100 to "C", 10 to "X", 9 to "IX", 5 to "V", 4 to "IV", 1 to "I").toMap()

    fun fromArabic(arabic: Int): String {
        var roman = ""
        var arabicDigit = arabic

        romans.forEach { (digit: Int, glyph: String) ->
            while (arabicDigit >= digit) {
                roman += glyph
                arabicDigit -= digit
            }
        }
        return roman
    }
}
