/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package RomanNumeral

import kotlin.test.Test
import kotlin.test.assertEquals

class RomanNumeralConverterTest {
    @Test
    fun convertFromArabic() {
        assertEquals("", RomanNumeralConverter.fromArabic(0))
        assertEquals("I", RomanNumeralConverter.fromArabic(1))
        assertEquals("II", RomanNumeralConverter.fromArabic(2))
        assertEquals("IV", RomanNumeralConverter.fromArabic(4))
        assertEquals("V", RomanNumeralConverter.fromArabic(5))
        assertEquals("VI", RomanNumeralConverter.fromArabic(6))
        assertEquals("X", RomanNumeralConverter.fromArabic(10))
        assertEquals("IX", RomanNumeralConverter.fromArabic(9))
        assertEquals("XI", RomanNumeralConverter.fromArabic(11))
        assertEquals("D", RomanNumeralConverter.fromArabic(500))
        assertEquals("C", RomanNumeralConverter.fromArabic(100))
        assertEquals("MMXIX", RomanNumeralConverter.fromArabic(2019))
        assertEquals("MMM", RomanNumeralConverter.fromArabic(3000))

    }
}
